version: '2'
services:
  server:
    build: .
    command: bash -l -c "yarn start"
    environment:
      - PORT=3000
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/node/app/google-service-account.json
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '3000:3000'
